# monitor=,addreserved, 0, 0, 0, 0 # custom reserved area

# HDMI port: mirror display. to see device name, use `hyprctl monitors`


xwayland {
  force_zero_scaling = true
}

# keyboard confs
input {
    kb_layout = br
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35

    # comment to get caps back
    kb_options = caps:escape 

    follow_mouse = 1
    off_window_axis_events = 2

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 0.7
    }
}

env = HYPRSHOT_DIR, $HOME/Pictures/Screenshots

# blur behavior
decoration:blur {
    enabled = false
    size = 7
    passes = 3
    xray = true # enable to avoid blur issues with stacked windows
    noise = 0.05
    contrast = 10
    ignore_opacity = true
    new_optimizations = true
    drop_shadow = false
}

cursor {
    no_hardware_cursors = true
}

gestures {
    # Habilita a troca de workspaces deslizando 3 dedos no touchpad
    workspace_swipe = true
    workspace_swipe_fingers = 3
}


# Desliga a tela do laptop ao fechar a tampa, e religa ao abrir
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, 1366x768@60, 0x0, 1"
